"""Explicit opt-in local PostgreSQL 18 test, with synthetic data and fake S3.

Creates its own short-lived localhost cluster. Never reads application config.
"""
import os
from pathlib import Path
import socket
import subprocess
import tempfile

from postgres_backup import Config, backup
from test_postgres_backup import FakeS3


def run(args, **kwargs):
    return subprocess.run(args, check=True, capture_output=True, timeout=60, **kwargs)


def main():
    # Remove ambient libpq and app DB settings; no .env or credential files read.
    env = {k: v for k, v in os.environ.items() if not k.startswith("PG")
           and k not in ("DATABASE_URL", "HMUSIC_BACKUP_DIRECT_DATABASE_URL")}
    env["PGPASSWORD"] = "synthetic-only"
    with tempfile.TemporaryDirectory(prefix="hmusic-pg18-roundtrip-") as folder:
        root = Path(folder)
        data = root / "cluster"
        with socket.socket() as listener:
            listener.bind(("127.0.0.1", 0))
            port = listener.getsockname()[1]
        run(["initdb", "-D", str(data), "--username=backup_test", "--auth=trust", "--no-locale"], env=env)
        started = False
        try:
            run(["pg_ctl", "-D", str(data), "-l", str(root / "postgres.log"), "-o",
                 f"-h 127.0.0.1 -p {port} -k {folder}", "-w", "start"], env=env)
            started = True
            psql = ["psql", "-X", "-h", "127.0.0.1", "-p", str(port), "-U", "backup_test", "-v", "ON_ERROR_STOP=1"]
            run(psql + ["-d", "postgres", "-c", "CREATE DATABASE synthetic_source"], env=env)
            run(psql + ["-d", "postgres", "-c", "CREATE DATABASE synthetic_restore"], env=env)
            sql = """
                CREATE TABLE synthetic_records (
                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  label text NOT NULL UNIQUE,
                  amount numeric(12,2), payload bytea, event_at timestamptz
                );
                INSERT INTO synthetic_records(label,amount,payload,event_at)
                SELECT 'synthetic-' || n, n * 1.25, decode('0001ff','hex'),
                       '2026-01-01T00:00:00Z'::timestamptz FROM generate_series(1,25) n;
                CREATE VIEW synthetic_view AS SELECT id,label FROM synthetic_records;
            """
            run(psql + ["-d", "synthetic_source", "-c", sql], env=env)
            s3 = FakeS3()
            config = Config(f"postgresql://backup_test:synthetic-only@127.0.0.1:{port}/synthetic_source",
                            "synthetic-local-only")
            manifest = backup(config, client=s3, temp_root=folder)
            archive = root / "restore.dump"
            archive.write_bytes(s3.objects[manifest["database"]["key"]][0])
            run(["pg_restore", "--exit-on-error", "--no-owner", "-h", "127.0.0.1", "-p", str(port),
                 "-U", "backup_test", "-d", "synthetic_restore", str(archive)], env=env)
            query = "SELECT count(*),sum(amount),min(encode(payload,'hex')),min(event_at) FROM synthetic_records; SELECT count(*) FROM synthetic_view;"
            source = run(psql + ["-At", "-d", "synthetic_source", "-c", query], env=env).stdout
            restored = run(psql + ["-At", "-d", "synthetic_restore", "-c", query], env=env).stdout
            assert source == restored and b"25|406.25|0001ff" in restored
            seq = run(psql + ["-At", "-d", "synthetic_restore", "-c",
                      "INSERT INTO synthetic_records(label) VALUES ('next-synthetic') RETURNING id"], env=env).stdout
            assert seq.splitlines()[0] == b"26"
            print("PASS: PostgreSQL 18 synthetic schema/data/view/sequence round trip; fake S3 SHA-256 verified.")
        finally:
            if started:
                run(["pg_ctl", "-D", str(data), "-m", "immediate", "-w", "stop"], env=env)


if __name__ == "__main__":
    main()
