"""Copy an H-Music SQLite database into an empty PostgreSQL database.

The script is intentionally repeatable: the destination schema is rebuilt only
when --replace is supplied. It prints and verifies per-table row counts.
"""

import argparse
import os
import sqlite3
import sys


def quote_ident(name):
    return '"' + name.replace('"', '""') + '"'


def postgres_type(sqlite_type):
    value = (sqlite_type or "TEXT").upper()
    if "INT" in value:
        return "BIGINT"
    if any(token in value for token in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in value:
        return "BYTEA"
    if any(token in value for token in ("NUM", "DEC")):
        return "NUMERIC"
    return "TEXT"


def sqlite_tables(connection):
    return [
        row[0]
        for row in connection.execute(
            """
            SELECT name FROM sqlite_master
            WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
            ORDER BY name
            """
        )
    ]


def create_table(source, destination, table):
    columns = source.execute(f"PRAGMA table_info({quote_ident(table)})").fetchall()
    primary_keys = [column for column in columns if column[5]]
    definitions = []
    identity_column = None
    for _, name, data_type, not_null, default_value, is_primary in columns:
        definition = f"{quote_ident(name)} {postgres_type(data_type)}"
        if len(primary_keys) == 1 and is_primary and postgres_type(data_type) == "BIGINT":
            definition = f"{quote_ident(name)} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            identity_column = name
        else:
            if not_null:
                definition += " NOT NULL"
            if default_value is not None:
                normalized = str(default_value)
                if normalized.upper() not in ("CURRENT_TIMESTAMP", "CURRENT_DATE"):
                    definition += f" DEFAULT {normalized}"
            if len(primary_keys) == 1 and is_primary:
                definition += " PRIMARY KEY"
        definitions.append(definition)
    if len(primary_keys) > 1:
        definitions.append(
            "PRIMARY KEY (" + ", ".join(quote_ident(column[1]) for column in primary_keys) + ")"
        )
    destination.execute(
        f"CREATE TABLE {quote_ident(table)} (" + ", ".join(definitions) + ")"
    )
    return [column[1] for column in columns], identity_column


def unique_indexes(source, destination, table):
    for index in source.execute(f"PRAGMA index_list({quote_ident(table)})").fetchall():
        _, index_name, is_unique = index[:3]
        if not is_unique or index_name.startswith("sqlite_autoindex"):
            continue
        columns = [
            row[2]
            for row in source.execute(f"PRAGMA index_info({quote_ident(index_name)})").fetchall()
        ]
        if columns:
            destination.execute(
                f"CREATE UNIQUE INDEX {quote_ident(index_name)} ON {quote_ident(table)} "
                f"({', '.join(quote_ident(column) for column in columns)})"
            )


def migrate(sqlite_path, database_url, replace=False):
    try:
        import psycopg
    except ImportError:
        raise SystemExit("Install psycopg before running the migration.")

    source = sqlite3.connect(sqlite_path)
    destination = psycopg.connect(database_url, autocommit=False)
    tables = sqlite_tables(source)
    report = []
    try:
        with destination.cursor() as cursor:
            if replace:
                cursor.execute("DROP SCHEMA public CASCADE")
                cursor.execute("CREATE SCHEMA public")
            existing = cursor.execute(
                "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'"
            ).fetchall()
            if existing:
                raise RuntimeError("Destination is not empty. Use --replace only for an approved rehearsal database.")

            identities = {}
            table_columns = {}
            for table in tables:
                columns, identity = create_table(source, cursor, table)
                table_columns[table] = columns
                identities[table] = identity

            for table in tables:
                columns = table_columns[table]
                rows = source.execute(f"SELECT * FROM {quote_ident(table)}").fetchall()
                if rows:
                    placeholders = ", ".join(["%s"] * len(columns))
                    cursor.executemany(
                        f"INSERT INTO {quote_ident(table)} "
                        f"({', '.join(quote_ident(column) for column in columns)}) VALUES ({placeholders})",
                        rows,
                    )
                unique_indexes(source, cursor, table)
                source_count = len(rows)
                destination_count = cursor.execute(
                    f"SELECT COUNT(*) FROM {quote_ident(table)}"
                ).fetchone()[0]
                report.append((table, source_count, destination_count))
                identity = identities[table]
                if identity:
                    maximum = cursor.execute(
                        f"SELECT MAX({quote_ident(identity)}) FROM {quote_ident(table)}"
                    ).fetchone()[0]
                    cursor.execute(
                        "SELECT setval(pg_get_serial_sequence(%s, %s), %s, %s)",
                        (table, identity, maximum or 1, maximum is not None),
                    )
        destination.commit()
    except Exception:
        destination.rollback()
        raise
    finally:
        destination.close()
        source.close()

    failed = False
    for table, source_count, destination_count in report:
        status = "OK" if source_count == destination_count else "MISMATCH"
        failed = failed or status != "OK"
        print(f"{status:8} {table:40} sqlite={source_count} postgres={destination_count}")
    if failed:
        raise SystemExit(1)
    print(f"Verified {len(report)} tables successfully.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sqlite", default=os.environ.get("HMUSIC_DB_PATH", "hmusic.db"))
    parser.add_argument("--database-url", default=os.environ.get("DATABASE_URL"))
    parser.add_argument("--replace", action="store_true")
    args = parser.parse_args()
    if not args.database_url:
        parser.error("--database-url or DATABASE_URL is required")
    migrate(args.sqlite, args.database_url, replace=args.replace)


if __name__ == "__main__":
    main()
